# - name: install docker 
#   hosts: monitors
#   tasks:
#   - name: install docker.io
#     become: yes
#     apt:
#       name: docker.io
#       state: present
#   - name: install docker-compose
#     become: yes
#     apt:
#       name: docker-compose
#       state: present
#   - name: test docker service is running
#     become: yes
#     service:
#       name: docker
#       state: started

- name: create exporter server
  hosts: node_exporters
  become: yes
  roles:
    - cadvisor
    - node-exporter
  tags: exporting

- name: create monitor server
  hosts: monitors
  become: yes
  roles:
    - prometheus
    - grafana
    - alertmanager
  tags: monitoring