route:
  receiver: 'telegram'
  group_by: ['alertname']
  group_wait: 10s

receivers:
  - name: 'telegram'
    telegram_configs:
      - send_resolved: true
        api_url: https://api.telegram.org
        chat_id: -622739777
        bot_token: '5517574482:AAGkzQRxHfd9b42jShLSEPcFRyFErGVVL7I'
        parse_mode: 'HTML'
