global:
  resolve_timeout: 1m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'telegram-notifications'
receivers:
- name: 'telegram-notifications'
  telegram_configs:
  - bot_token: '{{bot_token}}'
    chat_id: {{your_group_chat_id}}
    send_resolved: true
    api_url: 'https://api.telegram.org'
    parse_mode: 'Markdown'
    
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']