---
- name: Create alertmanager container
  docker_container:
    image: prom/alertmanager:v0.22.2
    name: alertmanager
    volumes:
      - ./alertmanager:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    ports:
    - 9093:9093
    # restart: unless-stopped
